### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by Alastor-NBL** [ApolloRIP/Gazelle#6]
I didn't notice a tracker in the codebase what tracker are you guys using?

**Comment by MasterOdin** [comment]
We use [Ocelot](https://github.com/ApolloRIP/Ocelot) which WCD showed as being pretty battle-tested, though have been experimenting with a python port, [Margay](https://github.com/ApolloRIP/Margay) though the latter is in no shape ready for production.

**Comment by itismadness** [comment]
The tracker is [Ocelot](https://github.com/ApolloRIP/Ocelot).

**Comment by Alastor-NBL** [comment]
Thanks for the reply. You like Shy Guy too lol. Which version you guys using 0.8 or 1.0 thanks?

**Comment by ligh7s** [comment]
Your search-fu is lacking. https://github.com/ApolloRIP/Ocelot

**Comment by itismadness** [comment]
1.0

**Comment by Alastor-NBL** [comment]
itismadness thanks for that.
